export const users = [
    {
        id: 1,
        name: "John Doe",
        email: "john@example.com",
        age: 28,
        job: "Software Engineer",
        place: "Kochi",
        salary: 45000,
    },
    {
        id: 2,
        name: "Jane Smith",
        email: "jane@example.com",
        age: 25,
        job: "UI/UX Designer",
        place: "Trivandrum",
        salary: 40000,
    },
    {
        id: 3,
        name: "Alex Johnson",
        email: "alex@example.com",
        age: 30,
        job: "Backend Developer",
        place: "Calicut",
        salary: 55000,
    },
    {
        id: 4,
        name: "Eve Dickson",
        email: "eve@example.com",
        age: 27,
        job: "QA Engineer",
        place: "Kollam",
        salary: 38000,
    },
    {
        id: 5,
        name: "Michael Brown",
        email: "michael@example.com",
        age: 32,
        job: "Project Manager",
        place: "Chennai",
        salary: 75000,
    },
    {
        id: 6,
        name: "Sophia Wilson",
        email: "sophia@example.com",
        age: 24,
        job: "Frontend Developer",
        place: "Bangalore",
        salary: 42000,
    },
    {
        id: 7,
        name: "David Lee",
        email: "david@example.com",
        age: 29,
        job: "DevOps Engineer",
        place: "Hyderabad",
        salary: 60000,
    },
    {
        id: 8,
        name: "Olivia Martin",
        email: "olivia@example.com",
        age: 26,
        job: "Data Analyst",
        place: "Mumbai",
        salary: 50000,
    },
    {
        id: 9,
        name: "James Anderson",
        email: "james@example.com",
        age: 31,
        job: "Full Stack Developer",
        place: "Pune",
        salary: 70000,
    },
];